## First ML - 붓꽃 품종 예측

In [2]:
!pip install scikit-learn

You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [1]:
from sklearn.datasets import load_iris               
from sklearn.tree import DecisionTreeClassifier       
from sklearn.model_selection import train_test_split  

In [2]:
import pandas as pd

#붓꽃 데이터 셋 로딩
iris = load_iris()

#피처(feature) 데이터 : numpy
#피처에는 sepal length, sepal width, petal length, petal width가 있음.
iris_data = iris.data

#레이블(결정 값) 데이터 : numpy
#label은 0(setosa), 1(versicolor), 2(virginica)로 되어있음
iris_label = iris.target
print('iris target 값 :', iris_label)
print('iris targer 명 :', iris.target_names)

#붓꽃 데이터 셋을 DataFrame으로
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris_label
iris_df

iris target 값 : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris targer 명 : ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [3]:
#학습용 데이터와 테스트용 데이터 분리 --> train_test_split()
#test_size : 전체 데이터 세트 중 테스트 데이터 세트 비율
#random_state : 호출할 때마다 같은 학습/테스트용 데이터 생성하기 위해 주어지는 난수 발생 값
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

In [4]:
#의사결정 트리를 이용해 학습과 예측

#DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

#학습 수행
dt_clf.fit(X_train, y_train)

#학습 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
pred = dt_clf.predict(X_test)

In [5]:
print(pred)
print(y_test)

[2 2 1 1 2 0 1 0 0 1 1 1 1 2 2 0 2 1 2 2 1 0 0 1 0 0 2 1 0 1]
[2 2 2 1 2 0 1 0 0 1 2 1 1 2 2 0 2 1 2 2 1 0 0 1 0 0 2 1 0 1]


In [6]:
#예측 성능 평가 - 정확도 측정
#예측한 붓꽃 품종과 실제 테스트 데이터 세트의 붓꽃 품종이 얼마나 맞는지 평가
from sklearn.metrics import accuracy_score
print('예측 정확도:{0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도:0.9333


## scikit-learn 익히기

### 내장된 데이터 셋 

datasets.load_boston(), datasets.load_breast_cancer(), datasets.load_iris(), ...

cf) fetch 계열 명령어는 데이터 크기가 커서 인터넷에서 내려받는 데이터

In [7]:
#붓꽃 데이터 세트의 구성
from sklearn.datasets import load_iris
iris_data = load_iris()
print(type(iris_data))    #sklearn.utils.Bunch 클래스 - 딕셔너리와 유사
print('붓꽃 데이터 세트의 키 :', iris_data.keys())

<class 'sklearn.utils.Bunch'>
붓꽃 데이터 세트의 키 : dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [8]:
#feature_names: 피처의 이름
print(type(iris_data.feature_names))
print(len(iris_data.feature_names))
print(iris_data.feature_names)

#target_names: 개별 레이블 이름
print(type(iris_data.target_names))
print(len(iris_data.target_names))
print(iris_data.target_names)

#iris_data.data / iris_data['data'] - 피처들의 데이터 값
print(type(iris_data.data))
print(iris_data.data.shape)
print(iris_data['data'])

#target: 분류 시 레이블 값, 회귀 시 숫자 결과값 데이터 세트
print(type(iris_data.target))
print(iris_data.target.shape)
print(iris_data.target)

<class 'list'>
4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
<class 'numpy.ndarray'>
3
['setosa' 'versicolor' 'virginica']
<class 'numpy.ndarray'>
(150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3

### model_selection 모듈

학습 데이터와 테스트 데이터 분리 / 교차 검증 분할 및 평가 / 하이퍼 파라미터 튜닝

In [9]:
#학습 데이터와 테스트 데이터 분리 - train_test_split()

#test_size : 전체 데이터 세트 중 테스트 데이터 세트 비율
#train_size : 전체 데이터 세트 중 학습용 데이터 세트 비율 - 잘 사용하지 않음
#shuffle : 데이터 섞을지 여부, 디폴트 : True
#random_state : 호출할 때마다 같은 학습/테스트용 데이터 생성하기 위해 주어지는 난수 발생 값

from sklearn.datasets import load_iris               
from sklearn.tree import DecisionTreeClassifier       
from sklearn.model_selection import train_test_split  
from sklearn.metrics import accuracy_score

iris_data = load_iris()
dt_clf = DecisionTreeClassifier()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print("예측 정확도:", accuracy_score(y_test, pred))

예측 정확도: 0.9555555555555556


학습 데이터 양을 일정 수준 이상으로 보장하는 것도 중요하지만, 다양한 데이터를 기반으로 예측 성능을 평가해보는 것도 중요

### 교차검증

해당 테스트 데이터에만 과적합되는 모델이 만들어져 다른 테스트용 데이터가 들어오는 경우에는 성능 저하 - 교차 검증 이용

여러 세트로 구성된 학습 데이터 세트와 검증 데이터 세트에서 학습과 평가 수행.(학습 데이터를 분할하여 학습 데이터와 검증 데이터로 나눔)

교차 검증 기반으로 1차 평가 한 뒤에 최종적으로 테스트 데이터로 평가

#### K 폴드 교차 검증

K 개의 데이터 폴드 세트를 만들어서 K 번만큼 각 폴드 세트에 학습과 검증 평가 반복 수행, K개의 예측 평가를 평균해서 K 폴드 평가 결과로 반영

In [10]:
from sklearn.tree import DecisionTreeClassifier       
from sklearn.model_selection import KFold  
from sklearn.metrics import accuracy_score
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

#5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy=[]
print('붓꽃 데이터 세트 크기:',features.shape[0])

붓꽃 데이터 세트 크기: 150


In [11]:
n_iter=0

#KFold 객체의 split() 호출하면 폴드 별 학습용, 검증용 데이터의 인덱스 반환
for train_index, test_index in kfold.split(features):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    #학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter+=1
    #반복 시마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print("\n#{0}교차 검증 정확도:{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}".format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스: {1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)
    
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))
    


#1교차 검증 정확도:1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#1 검증 세트 인덱스: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2교차 검증 정확도:0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#2 검증 세트 인덱스: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3교차 검증 정확도:0.8667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#3 검증 세트 인덱스: [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4교차 검증 정확도:0.9333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#4 검증 세트 인덱스: [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5교차 검증 정확도:0.7333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#5 검증 세트 인덱스: [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9


#### Stratified K 폴드



불균형한 분포도를 가진 레이블(결정 클래스) 데이터 집합을 위한 K 폴드 방식

불균형한 분포도를 가진 레이블 : 특정 레이블 값이 특이하게 많거나 매우 적어서 값의 분포가 한쪽으로 치우치는 것

In [12]:
from sklearn.datasets import load_iris               

import pandas as pd
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [13]:
from sklearn.model_selection import KFold 
kfold = KFold(n_splits=3)
n_iter=0
for train_index, test_index in kfold.split(iris_df):
    n_iter+=1
    label_train=iris_df['label'].iloc[train_index]
    label_test=iris_df['label'].iloc[test_index]
    print("##교차검증 :", n_iter)
    print("학습 레이블 데이터 분포\n", label_train.value_counts())
    print("검증 레이블 데이터 분포\n", label_test.value_counts())

##교차검증 : 1
학습 레이블 데이터 분포
 1    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포
 0    50
Name: label, dtype: int64
##교차검증 : 2
학습 레이블 데이터 분포
 0    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포
 1    50
Name: label, dtype: int64
##교차검증 : 3
학습 레이블 데이터 분포
 0    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포
 2    50
Name: label, dtype: int64


3개의 폴드세트로 만들어지는 학습 레이블과 검증 레이블이 완전히 다른 값

첫번쨰 교차검증에서는 학습 레이블은 1,2 값만 추출되었고 검증 레이블은 0만 추출되어서 0을 전혀 학습하지 못하고 0을 예측하지 못한다.

이런 유형으로 교차 검증 데이터 세트를 분할하면 검증 예측 정확도는 0이 될 수 밖에 없다.

In [14]:
#StratifiedKFold는 레이블 데이터 분포도에 따라 학습/검증 데이터를 나눈다
from sklearn.model_selection import StratifiedKFold 
skf = StratifiedKFold(n_splits=3)
n_iter=0
for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter+=1
    label_train=iris_df['label'].iloc[train_index]
    label_test=iris_df['label'].iloc[test_index]
    print("##교차검증 :", n_iter)
    print("학습 레이블 데이터 분포\n", label_train.value_counts())
    print("검증 레이블 데이터 분포\n", label_test.value_counts())

##교차검증 : 1
학습 레이블 데이터 분포
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포
 0    17
1    17
2    16
Name: label, dtype: int64
##교차검증 : 2
학습 레이블 데이터 분포
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포
 0    17
2    17
1    16
Name: label, dtype: int64
##교차검증 : 3
학습 레이블 데이터 분포
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포
 1    17
2    17
0    16
Name: label, dtype: int64


학습 레이블과 검증 레이블 데이터 값의 분포도가 동일하게 할당되었다.

In [15]:
#StratifiedKFold 이용하여 학습 및 검증

from sklearn.tree import DecisionTreeClassifier       
from sklearn.metrics import accuracy_score

import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

skfold=StratifiedKFold(n_splits=3)
n_iter = 0
cv_accuracy=[]

#StratifiedKFold의 split()호출 시 레이블 데이터 세트도 추가 입력 필요
for train_index, test_index in skf.split(features, label):
    #split()으로 반환된 인덱스 이용해 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    #학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    
    #반복 시마다 정확도 측정
    n_iter+=1
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print("\n#{0}교차 검증 정확도:{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}"
          .format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스: {1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)
    
print('\n##교차 검증별 정확도:', np.round(cv_accuracy, 4))
print('## 평균 검증 정확도:', np.mean(cv_accuracy))


#1교차 검증 정확도:0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#1 검증 세트 인덱스: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2교차 검증 정확도:0.94, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#2 검증 세트 인덱스: [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3교차 검증 정확도:0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#3 검증 세트 인덱스: [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

##교차 검증별 정확도: [0.98 0.94 0.98]
## 평균 검증 정확도: 0.9666666666666667


일반적으로 분류(Classification)에서의 교차 검증은 Stratified K 폴드로 분할되어야 한다.

회귀(Regression)에서는 Stratified K 폴드가 지원되지 않는다. 회귀의 결정값은 이산값 형태의 레이블이 아니라 연속된 숫자값이기 때문에 결정값별로 분포를 정하는 의미가 없기 때문이다.

#### 교차 검증을 간편하게 제공해주는 사이킷런의 API

cross_val_score(estimator, X, y=None, scoring=None, cv=None, ...)

estimator: 분류 알고리즘 클래스인 Classifier 또는 회귀 알고리즘 클래스인 Regression 의미

X: 피처 데이터 세트, y: 레이블 데이터 세트, scoring: 예측 성능 평가 지표, cv: 교차 검증 폴드 수

In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

import numpy as np

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data=iris_data.data
label = iris_data.target

#성능 지표는 정확도(accuracy), 교차 검증 세트 3개
#cross_val_score() 수행 후 scoring 파라미터로 지정된 성능 지표 측정값을 배열 형태로 반환
scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print('교차 검증별 정확도:', np.round(scores, 4))
print('평균 검증 정확도:',np.round(np.mean(scores), 4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


cross_val_score() API는 내부에서 Estimator을 학습, 예측, 평가시켜주므로 간단하게 교차검증 수행 가능

classifier가 입력되면 Stratified K 폴드 방식으로 레이블값 분포에 따라 학습/테스트 세트 분할 - 단 하나의 평가 지표만 가능

cf) cross_validate : 여러 개의 평가 지표 반환 가능, 성능 평가 지표와 수행 시간도 같이 제공

### GridSearchCV - 교차검증과 최적 하이퍼 파라미터 튜닝

하이퍼 파라미터 : 머신러닝 알고리즘을 구성하는 주요 구성 요소, 이 값을 조정하여 알고리즘의 예측 성능 개선

GridSearchCV API를 이용해 Classifier나 Regressor 같은 알고리즘에 사용되는 하이퍼 파라미터를 순차적으로 적용하면서 편리하게 최적의 파라미터 도출 가능, 교차 검증 기반, (CV 값 * 파라미터 조합 개수) 만큼 학습/평가 실행

In [17]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
import pandas as pd

#데이터를 로딩하고 학습데이터와 테스트 데이터 분리
iris_data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)
dtree = DecisionTreeClassifier()

#DecisionTreeClassifier의 중요 하이퍼 파라미터인 max_depth, min_samples_split
#파라미터를 딕셔너리 형태로 설정(하이퍼 파라미터 명칭은 문자열로, 값은 리스트로)
parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}

#param_grid의 하이퍼 파라미터를 3개의 train, test set fold로 나누어 테스트 수행 설정
## refit=True : default, 가장 좋은 파라미터 설정으로 재학습
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

#학습 데이터를 cv 값만큼 폴딩 세트로 분할해 param_grid에 기술된 하이퍼 파라미터를 순차적으로 변경하면서 학습/평가 수행
grid_dtree.fit(X_train, y_train)

#결과는 cv_results_속성에 저장, 딕셔너리 형태로 key값과 리스트 형태의 value 값 가짐
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score',
          'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

params : 수행할때마다 적용된 개별 하이퍼 파라미터 값

rank_test_score : 하이퍼 파라미터별로 성능이 좋은 score 순위(1이 가장 뛰어난 순위)

mean_test_score : 개별 하이퍼 파라미터별로 CV의 폴딩 테스트 세트에 대해 총 수행한 평가의 평균값

In [18]:
print('GridSearchCV 최적 파라미터:', grid_dtree.best_params_)
print('GridSearchCV 최적 정확도:{0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최적 정확도:0.9750


In [19]:
from sklearn.metrics import accuracy_score

#refit=True : GridSearchCV가 최적 하이퍼 파라미터로 Estimator를 학습해 best_estimator_에 저장
#이미 학습된 estimator 반환
estimator = grid_dtree.best_estimator_

#GridSearchCV의 best_estimator_는 이미 최적 학습이 되었으므로 별도 학습 X
pred = estimator.predict(X_test)
print('테스트 데이터 세트 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

테스트 데이터 세트 정확도: 0.9667


## 데이터 전처리

ML 알고리즘은 데이터에 기반하기 때문에 어떤 데이터를 입력으로 가지냐에 따라 결과도 달라짐.

데이터에 대해 미리 처리해야할 사항

1. 결손값(NaN, Null) 허용 X - 피처의 평균값 등으로 대체, 해당 피처 드롭, ...
2. 문자열 값을 입력 값으로 허용 X - 인코딩하여 숫자형으로 변환
   - 카테코리 형 피처 : 코드 값으로 표현
   - 텍스트형 피처 : 피처 벡터화 등으로 벡터화, 불필요한 피처라면 삭제(단순히 데이터 로우 식별하는 식별자 피처의 경우)

### 데이터 인코딩

#### 레이블 인코딩(Label encoding)

카테고리 피처를 숫자형 카테고리 값으로 변환

but 숫자 변환 값이 크고 작음에 따라 순서나 중요도로 인식되는 특정 ML 알고리즘에서는 예측 성능 떨어짐

선형회귀 같은 ML 알고리즘에는 적용 X, 트리 계열 ML 알고리즘 적용 O

In [20]:
from sklearn.preprocessing import LabelEncoder

items=['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

#LabelEncoder를 객체로 생성한 후 fit(), transform()으로 레이블 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)

#문자열이 어떤 값으로 인코딩 되었는지 확인(0번부터 순서대로 변환된 인코딩 값에 대한 원본값 가짐)
print('인코딩 클래스:', encoder.classes_)

#인코딩된 값을 다시 디코딩
print('디코딩 원본값:',encoder.inverse_transform([4,5,2,0,1,1,3,3]))

인코딩 변환값: [0 1 4 5 3 3 2 2]
인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']
디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


#### 원-핫 인코딩(One-Hot Encoding)

피처 값의 유형에 따라 새로운 피처를 추가해(피처 고유 값을 열 형태로 차원 변환한 뒤) 고유 값에 해당하는 칼럼에만 1을 표시하고 나머지 칼럼에는 0 표시

OneHotEncoder 클래스로 변환 가능

주의) 모든 문자열 값이 숫자형 값으로 변환되어야 함, 입력값으로 2차원 데이터 필요

In [21]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

#먼저 숫자 값으로 변환하기 위해 LabelEncoder로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
#2차원 데이터로 변환
labels = labels.reshape(-1, 1)

#원-핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [22]:
#get_dummies() 사용하여 문자열 카테고리 값을 숫자형으로 변환할 필요 없이 바로 원-핫 인코딩
import pandas as pd
df = pd.DataFrame({'item':['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

### 피처 스케일링과 정규화

서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업

- 표준화(Standardization)

데이터의 피처 각각이 평균 0, 분산 1인 가우시간 정규 분포를 가진 값으로 변환

(원래 값 - 피처의 평균) / 피처의 표준편차 로 계산

- 정규화(Normalization)

서로 다른 피처의 크기를 통일하기 위해 크기 변환

즉, 개별 데이터의 크기를 모두 똑같은 단위로 변경(최소 0 ~ 최대 1)

(원래 값 - 피처의 최소값) / (피처의 최댓값 - 피처의 최솟값) 로 계산

- 사이킷런 전처리에서 제공하는 Normalizer 모듈

일반적인 정규화와 약간의 차이가 존재

선형대수에서의 정규화 개념이 적용되었으며, 개별 벡터의 크기를 맞추기 위해 변환. 즉, 개별 벡터를 모든 피처의 벡터의 크기로 나눠줌

!!! 일반적 의미의 표준화와 정규화 : 피처 스케일링, 선형 대수 개념의 정규화 : 벡터 정규화 !!!

### StandardScaler

피처 스케일링의 표준화 지원. 즉, 개별 피처를 평균이 0이고 분산이 1인 값으로 변환

RBF 커널을 이용하는 서포트 벡터 머신, 선형회귀, 로지스틱 회귀에서 중요

In [23]:
from sklearn.datasets import load_iris
import pandas as pd

#붓꽃 데이터세트 로딩하고 DataFrame으로 변환
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature의 평균 값')
print(iris_df.mean())
print('\nfeature의 분산 값')
print(iris_df.var())

feature의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [24]:
from sklearn.preprocessing import StandardScaler

#StandardScaler 객체 생성
scaler = StandardScaler()
#StandardScaler로 데이터 세트 변환
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

#transform()시 스케일 변환된 데이터 세트가 numpy ndarray로 변환되므로 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature의 분산 값')
print(iris_df_scaled.var())

feature의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


### MinMaxScaler

데이터 값을 0과 1 사이의 범위 값으로 변환, 음수 값 있으면 -1에서 1 값으로 변환

데이터 분포가 가우시안 분포가 아닐 떄 Min, Max Scale 적용 가능

In [25]:
from sklearn.preprocessing import MinMaxScaler

#MinMaxScaler 객체 생성
scaler = MinMaxScaler()
#MinMaxScaler로 데이터 세트 변환
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

#transform()시 스케일 변환된 데이터 세트가 numpy ndarray로 변환되므로 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature의 최솟값')
print(iris_df_scaled.min())
print('\nfeature의 최댓값')
print(iris_df_scaled.max())

feature의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


### 학습/테스트 데이터 스케일링 변환 시 유의점

- fit() : 데이터 변환을 위한 기준 정보 설정

- transform() : 설정된 정보를 이용해 데이터 변환

- fit_transform() : fit, transform 한번에 적용

학습 데이터에 fit(), transform() 적용하면 테스트 데이터에는 다시 fit()을 수행하지 않고 학습 데이터에 fit()을 수행한 결과를 이용해 transform()을 적용

즉, 학습 데이터로 fit()이 적용된 스케일링 기준 정보를 그대로 테스트 데이터에 적용, 그렇지 않으면 학습 데이터와 테스트 데이터의 스케일링 기준 정보가 달라짐.

In [26]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

#Scaler 클래스의 fit, transform은 2차원 이상 데이터만 가능
train_array = np.arange(0, 11).reshape(-1, 1)
test_array = np.arange(0, 6).reshape(-1, 1)

scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
print('원본 train_array 데이터: ', np.round(train_array.reshape(-1), 2))
print('Scaled된 train_array 데이터: ', np.round(train_scaled.reshape(-1), 2))

#test_array에 Scale변환 할 때는 반드시 fit()호출하지 않고 transform()만으로 변환해야 함
test_scaled = scaler.transform(test_array)
print('\n원본 test_array 데이터: ', np.round(test_array.reshape(-1), 2))
print('Scaled된 test_array 데이터: ', np.round(test_scaled.reshape(-1), 2))

원본 train_array 데이터:  [ 0  1  2  3  4  5  6  7  8  9 10]
Scaled된 train_array 데이터:  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

원본 test_array 데이터:  [0 1 2 3 4 5]
Scaled된 test_array 데이터:  [0.  0.1 0.2 0.3 0.4 0.5]


1. 전체 데이터의 스케일링 변환 적용한 뒤 학습과 테스트 데이터 분리

2. 1이 여의치 않으면 테스트 데이터 변환 시에는 fit(), fit_transform() 적용하지 않고 학습 데이터로 이미 fit()된 Scaler 객체 이용해 transform()으로 변환

PCA와 같은 차원 축소 변환이나 텍스트의 피처 벡터화 변환 작업 시에도 동일하게 적용