In [1]:
import numpy as np

In [3]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d[0:2, :])

[[1 2 3]
 [4 5 6]]


In [5]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d[[0,2],1])

[2 8]


In [6]:
array1d = np.arange(1,10)
print(array1d[array1d > 5])

[6 7 8 9]


In [7]:
org_array = np.array([3,1,9,5])
#np.sotr()는 원 행렬 유지한 채 정렬 행렬 반환
sort_array1 = np.sort(org_array)
print(sort_array1)
print(org_array)

#array.sort()는 원 행렬 자체를 정렬하고 None 반환
sort_array2 = org_array.sort()
print(sort_array2)
print(org_array)

#내림차순
sort_array_desc = np.sort(org_array)[::-1]
print(sort_array_desc)

[1 3 5 9]
[3 1 9 5]
None
[1 3 5 9]
[9 5 3 1]


In [8]:
array2d = np.array([[8,12],
                    [7,1]])
#row방향 축으로 정렬(각 열이 오름차순됨)
print(np.sort(array2d, axis = 0))
#col방향 축으로 정렬(각 행이 오름차순됨)
print(np.sort(array2d, axis = 1))

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [9]:
name_array = np.array(["John","Mike","Sarah","Kate","Samuel"])
score_array = np.array([78,95,84,98,88])
#행렬 정렬 시 원본 행렬의 인덱스
sort_indices_asc = np.argsort(score_array)

print(sort_indices_asc)
print(name_array[sort_indices_asc])

[0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [10]:
#선형대수
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])
print(np.dot(A,B))
print(np.transpose(A))

[[ 58  64]
 [139 154]]
[[1 4]
 [2 5]
 [3 6]]
